### ISSUE TITLE
add <&uart0_rts> to pinctrl

### ISSUE THREAD

**Issue by Tonymac32** [Miouyouyou/RockMyy#5]
https://github.com/Miouyouyou/RockMyy/blob/df2ada851ed8c24d81cabb3b9976e1903387c48e/patches/kernel/v4.17/DTS/0015-ARM-DTS-rk3288-tinker-Enabling-SDIO-and-Wifi.patch#L137

pinctrl-0 = <&uart0_xfer>, <&uart0_cts>, <&uart0_rts>;

makes the GPIO juggling less on Bluetooth.

**Comment by Miouyouyou** [comment]
Ah indeed, I'll add that tonight.

**Comment by Miouyouyou** [comment]
The patch is now broken into two parts.

https://github.com/Miouyouyou/RockMyy/blob/DRMFailing417rc5/patches/kernel/v4.17/DTS/0013-ARM-DTS-rk3288-tinker-Enabling-SDIO-and-Wifi.patch
https://github.com/Miouyouyou/RockMyy/blob/DRMFailing417rc5/patches/kernel/v4.17/DTS/0014-ARM-DTS-rk3288-tinker-Setup-the-Bluetooth-UART-pins.patch

Now, I'm having some issues with the DRM calls but... I have no idea why ! I had X11 working fine with the rc4 but not the rc5. I'll have to reexamine that tomorrow, since downloading a kernel from git.kernel.org is now capped at 100kb/sec it seems.

**Comment by Miouyouyou** [comment]
Okay, the new graphics card bug is fixed. It was due to something completely different.

**Comment by Miouyouyou** [comment]
I still have to reintegrate these patch on 5.6 kernels. But, that's another issue.
